all:
	javac -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. *.java
nc:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main nc
default:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main default