all:
	javac -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. *.java
nc:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main nc
default:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main default
ncChart:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main nc chart
ncLog:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main nc true
fso:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main fso
fsoChart:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main fso chart
fsoLog:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main fso true
multi:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main multi
multiChart:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main multi chart
multiLog:
	java -cp lib/jcommon-1.0.23.jar:lib/jfreechart-1.0.19.jar:. Main multi true